// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIXDTqbqaZjIPJFCqocJLjz9bbklGH4M',
    appId: '1:527314231266:web:f4b9a344c48b004558a3bb',
    messagingSenderId: '527314231266',
    projectId: 'rescuecare',
    authDomain: 'rescuecare.firebaseapp.com',
    databaseURL: 'https://rescuecare-default-rtdb.firebaseio.com',
    storageBucket: 'rescuecare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY2tZ6FWWRhcgoZMKSPsMDRu69cj41tws',
    appId: '1:527314231266:android:7fe92204c5f7300458a3bb',
    messagingSenderId: '527314231266',
    projectId: 'rescuecare',
    databaseURL: 'https://rescuecare-default-rtdb.firebaseio.com',
    storageBucket: 'rescuecare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-hpKPkoOJkoUm7zu-Up3fHo7yQztOzA',
    appId: '1:527314231266:ios:60e76b3614496ce258a3bb',
    messagingSenderId: '527314231266',
    projectId: 'rescuecare',
    databaseURL: 'https://rescuecare-default-rtdb.firebaseio.com',
    storageBucket: 'rescuecare.appspot.com',
    iosBundleId: 'com.example.resquecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-hpKPkoOJkoUm7zu-Up3fHo7yQztOzA',
    appId: '1:527314231266:ios:60e76b3614496ce258a3bb',
    messagingSenderId: '527314231266',
    projectId: 'rescuecare',
    databaseURL: 'https://rescuecare-default-rtdb.firebaseio.com',
    storageBucket: 'rescuecare.appspot.com',
    iosBundleId: 'com.example.resquecare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuIXDTqbqaZjIPJFCqocJLjz9bbklGH4M',
    appId: '1:527314231266:web:2485d4d375224ee458a3bb',
    messagingSenderId: '527314231266',
    projectId: 'rescuecare',
    authDomain: 'rescuecare.firebaseapp.com',
    databaseURL: 'https://rescuecare-default-rtdb.firebaseio.com',
    storageBucket: 'rescuecare.appspot.com',
  );
}
